initial commit
fncischen/Preprocessing-I pull request #1
Opened 2019-01-16 21:34 UTC by fncischen

@ryanboris Resume Website - PreProcessing HTML.

2019-01-16 22:57 UTC, secantsquared approved these changes
@fncischen 
O M G
WOW

Without even the content fully in there and even thought is still somewhat in the skeleton phase this layout...

wow

totally memorable, aesthetic and impressive
wow

2019-01-17 02:28 UTC, secantsquared requested changes
Take a look at the fluidity of the nav as is gets smaller - overall great job

2019-01-17 02:28 UTC, secantsquared commented on less/index.less
> +						padding: 15%;
```suggestion
						padding: 15%;
```

i think this padding may be messing up the a tags when the view port changes.

maybe try 
```css
padding: 10px 5%
```

2019-01-17 10:15 UTC, fncischen commented on less/index.less
> +						padding: 15%;
I got a chance to take a look at this this evening - still having the same issues, after adding the padding! Would love to hop on a zoom call later this coming afternoon to clarify.

2019-01-27 05:04 UTC, secantsquared approved these changes

2019-01-27 05:04 UTC, merged